import type { GameModule } from './games.types'

export const gamesRegistry: GameModule[] = [
  { id: 'nem-ferrando', name: 'Nem Ferrando', shortDescription: 'Curiosidades numéricas, palpites absurdos e muitos Ferros para quem errar feio.', description: 'Um jogo de cartas com curiosidades numéricas para jogar em grupo.', route: '/games/nem-ferrando', minPlayers: 2, maxPlayers: 12, isAvailableOffline: true, isPremium: false, status: 'available', iconName: 'cards', coverImage: '/assets/games/nem-ferrando.jpg', tags: ['cartas', 'grupo', 'offline', 'festa'] },
  { id: 'impostor-da-palavra', name: 'Impostor da Palavra', shortDescription: 'Descubra quem está fingindo saber a palavra.', description: 'Jogo social de dedução com palavras e papéis secretos.', route: '/games/impostor-da-palavra', minPlayers: 3, maxPlayers: 12, isAvailableOffline: true, isPremium: false, status: 'available', iconName: 'mask', coverImage: '/assets/games/impostor-palavra.jpg', tags: ['dedução', 'palavras', 'grupo', 'offline'] },
  { id: 'taboo', name: 'Dica Proibida', shortDescription: 'Descreva a palavra sem usar as pistas proibidas.', description: 'Um desafio de vocabulário contra o tempo.', route: '/games/taboo', minPlayers: 2, isAvailableOffline: true, isPremium: false, status: 'available', iconName: 'message-circle-off', coverImage: '/assets/games/dica-proibida.jpg', tags: ['palavras', 'times', 'offline'] },
  { id: 'quem-sou-eu', name: 'Quem Sou Eu', shortDescription: 'Escreva até 5 palavras, coloque o celular na testa e tente adivinhar.', description: 'Adivinhação rápida, simples e divertida para qualquer grupo.', route: '/games/quem-sou-eu', minPlayers: 2, isAvailableOffline: true, status: 'available', iconName: 'user-round-search', coverImage: '/assets/games/quem-sou-eu.webp', tags: ['adivinhação', 'grupo', 'palavras', 'offline'] },
  { id: 'adedonha', name: 'Adedonha', shortDescription: 'Crie temas, compartilhe por QR e preencha respostas no próprio celular.', description: 'O clássico jogo de palavras e categorias com folha digital para cada jogador.', route: '/games/adedonha', minPlayers: 2, isAvailableOffline: true, status: 'available', iconName: 'list-letters', coverImage: '/assets/games/adedonha.webp', tags: ['palavras', 'rápido', 'offline'] },
  { id: 'mimica', name: 'Mímica', shortDescription: 'Faça a galera adivinhar sem dizer uma palavra.', description: 'Desafios de interpretação individual ou em equipes.', route: '/games/mimica', minPlayers: 2, isAvailableOffline: true, status: 'available', iconName: 'drama', coverImage: '/assets/games/mimica.webp', tags: ['mímica', 'equipes', 'festa', 'offline'] },
  { id: 'top-10', name: 'Top 10', shortDescription: 'Descubra listas ranqueadas e some mais pontos nas primeiras posições.', description: 'Um jogo de rankings ocultos para jogar com mediador, individualmente ou em equipes.', route: '/games/top-10', minPlayers: 2, maxPlayers: 12, isAvailableOffline: true, isPremium: false, status: 'available', iconName: 'list-ordered', tags: ['ranking', 'listas', 'equipes', 'offline'] },
  { id: 'cidade-dorme', name: 'Cidade Dorme', shortDescription: 'Papéis secretos, blefes e uma cidade em perigo.', description: 'Dedução social com narrador e papéis secretos.', route: '/games/cidade-dorme', minPlayers: 4, maxPlayers: 12, isAvailableOffline: true, status: 'available', iconName: 'moon', coverImage: '/assets/games/cidade-dorme.webp', tags: ['dedução', 'papéis'] },
  { id: 'jogo-da-velha', name: 'Jogo da Velha', shortDescription: 'Três símbolos em linha vencem a rodada.', description: 'O clássico jogo de estratégia para duas pessoas.', route: '/games/jogo-da-velha', minPlayers: 2, maxPlayers: 2, isAvailableOffline: true, status: 'coming-soon', iconName: 'grid-3x3', tags: ['estratégia', 'dupla'] },
  { id: 'damas', name: 'Damas', shortDescription: 'Capture as peças e domine o tabuleiro.', description: 'Jogo tradicional de estratégia em tabuleiro.', route: '/games/damas', minPlayers: 2, maxPlayers: 2, isAvailableOffline: true, status: 'coming-soon', iconName: 'circle-dot', tags: ['tabuleiro', 'estratégia'] },
  { id: 'ludo', name: 'Ludo', shortDescription: 'Leve todas as suas peças até a chegada.', description: 'Corrida de tabuleiro para toda a galera.', route: '/games/ludo', minPlayers: 2, maxPlayers: 4, isAvailableOffline: true, status: 'coming-soon', iconName: 'dices', tags: ['tabuleiro', 'família'] },
]

export function getGameById(id: string) { return gamesRegistry.find((game) => game.id === id) }
